apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-three
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://github.com/st3w4r/argocd-apps.git
    targetRevision: HEAD
    path: apps/demo-three
  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
