apiVersion: apps/v1
kind: Deployment
metadata: 
  name: guestbook-two
spec: 
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-two
  template:
    metadata:
      labels:
        app: guestbook-two
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          name: guestbook-two
          ports:
          - containerPort: 80
